import { useState } from 'react';
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';
import Form from 'react-bootstrap/Form';
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';
import logoA from '../../public/ArquimaA.png'
import Image from 'next/image';

function ModalTerminos(props) {

  return (
    <>
      <Modal
        show={props.show}
        onHide={props.onHide}
        backdrop="static"
        keyboard={false}
        size='xl'
      >
        <Modal.Header>
          <Modal.Title>
            <Image className='img-fluid' alt='logoA' src={logoA} width={150} height={150} />
            Términos y condiciones
          </Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <Tabs
            defaultActiveKey="privacidad"
            id="uncontrolled-tab-example"
            className="mb-3"
          >
            <Tab eventKey="privacidad" title="Aviso de Privacidad">
              <div className='text-start'>
                <h6 className='text-center'><b>Aviso de Privacidad</b></h6>
                <h6 className='text-center mb-3'><b><u>"ARQUIMA"</u></b></h6>
                <p>Su privacidad y confianza son muy importantes para “SERVICIOS Y ASESORIAS EN ARQUITECTURA ARQUIMA S.A.S. DE C.V. (En los sucesivo “ARQUIMA”), por ello, queremos asegurarnos de que conozca como salvaguardamos la integridad, privacidad y protección de sus datos personales, en apego a la Ley Federal de Protección de Datos Personales en Posesión de los Particulares publicada en el Diario Oficial de la Federación el día 5 de julio de 2010 y a su respectivo Reglamento publicado en el Diario Oficial de la Federación el día 21 de diciembre de 2011.</p>
                <p>“ARQUIMA” tiene la obligación de cumplir con las medidas administrativas, legales y de seguridad suficientes para proteger aquellos datos personales que haya recabado para las finalidades que serán descritas en la presente política de privacidad.</p>
                <p>“ARQUIMA” se compromete a velar para que se cumplan todos los principios legales de protección de datos personales y manifestamos nuestro compromiso para que se respete en todo momento, por nosotros y por nuestros empleados, la presente política de privacidad.</p>
                <p>Todo lo anterior se realiza con el objetivo de que usted tenga pleno control y decisión sobre sus datos personales, a fin de garantizar el derecho de autodeterminación informativa. Por ello, le recomendamos que lea atentamente la siguiente información:</p>
                <p><b>1. Datos del Responsable</b></p>
                <p>“ARQUIMA”, con domicilio en Av Niños Héroes #2987 interior 109, Colonia Jardines del Bosque, en Guadalajara, Jalisco, C.P. 44520, con teléfono +52 33 1317 8258, y correo electrónico serviciosarquima@gmail.com, es responsable del tratamiento de los datos personales que nos proporcione de conformidad con lo dispuesto por el presente Aviso de Privacidad.</p>
                <p><b>2. Datos Personales</b></p>
                <p>“ARQUIMA” recabará de usted los datos personales que sean necesarios para la adecuada prestación de servicios los cuales incluyen los siguientes:</p>
                <p className='ms-4'>1. De los Usuarios de los Servicios datos de identificación: (i) nombre(s), apellido paterno y apellido materno, o bien, denominación o razón social; (ii) domicilio; (iii) número telefónico fijo o celular; (iv) correo electrónico, (v) cuentas de redes sociales, (vi) RFC, (vii) CURP. Igualmente Igualmente, se solicitará cierta información a los Usuarios como lo es: empresa o grupo que eres dueño o trabajas para, reseña de la empresa o grupo que eres dueño o trabajas para, entre otras, la cual quedará debidamente resguardada por “ARQUIMA” y será exclusivamente utilizada para los fines de los servicios que se ponen a disposición del Usuario.</p>
                <p>Usted se compromete que los datos que proporcione a “ARQUIMA” sean verídicos, completos y exactos. Cualquier dato falso, incompleto o inexacto será de su exclusiva responsabilidad.</p>
                <p><b>3. Finalidad del tratamiento de datos</b></p>
                <p>Los datos personales que nos ha proporcionado serán utilizados para los fines propios de la Sociedad y de las actividades relativas al desarrollo de dichos fines como lo son:</p>
                <p>A. De los Usuarios de los Servicios: De los clientes o usuarios de los servicios ofrecidos a través de las plataformas de “ARQUIMA” usaremos los datos que nos proporcione para la prestación de los servicios que ponemos a su disposición, entendiendo que nuestros servicios son personalizados, o anterior con la intención de otorgar soluciones y propuestas de trabajo particularizadas a Usted. </p>
                <p><b>4. Transferencia de datos</b></p>
                <p>“ARQUIMA” no transferirá sus datos personales a terceros.</p>
                <p><b>5. Revocación del Consentimiento</b></p>
                <p>En todo momento usted podrá revocar el consentimiento que nos ha otorgado para el tratamiento de sus datos personales, a fin de que dejemos de hacer uso de los mismos, siempre y cuando se encuentre previsto en los supuestos de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares.</p>
                <p>Para ello es necesario que presente su petición físicamente en la oficina de privacidad de “ARQUIMA” o en medios electrónicos a través de correo electrónico a la siguiente dirección: serviciosarquima@gmail.com </p>
                <p>Su petición deberá ir acompañada de su identificación y deberá señalar con claridad los datos personales respecto de los cuales desea sea revocado el consentimiento de tratamiento.</p>
                <p>Tendremos un plazo máximo de 20 días para atender su petición y le informaremos sobre la procedencia de la misma a través de correo electrónico.</p>
                <p><b>6. Medios para Ejercer los Derechos Arco</b></p>
                <p>Conforme a la Ley Federal de Protección de Datos Personales en Posesión de Particulares, el titular por sí o mediante representante legal debidamente acreditado, a partir del 06 de enero de 2012 podrá ejercer sus derechos de acceso, rectificación, cancelación u oposición directamente ante el Responsable del Tratamiento “SERVICIOS Y ASESORIAS EN ARQUITECTURA ARQUIMA S.A.S. DE C.V.” en el correo serviciosarquima@gmail.com </p>
                <p>En caso de elegir el correo postal, lo deberá de hacer al siguiente domicilio: Niños Héroes #2987 interior 109, Colonia Jardines del Bosque, en Guadalajara, Jalisco, C.P. 44520.</p>
                <p>I. Acceso.- Usted podrá solicitar en todo momento conocer qué datos suyos han sido recabados y conserva el responsable.</p>
                <p>II. Rectificación.- En caso de que alguno de sus datos sea inexacto o incompleto podrá solicitar su corrección, debiendo adjuntar la documentación que acredite dicha modificación.</p>
                <p>III. Cancelación.- Podrá solicitarse en todo momento la cancelación de los datos; en caso de ser procedente la solicitud, los datos entrarán al período de bloqueo en el cual no podrán ser tratados de ninguna manera para su posterior supresión.</p>
                <p>“ARQUIMA” podrá conservarlos exclusivamente para efectos de las responsabilidades nacidas del tratamiento. El periodo de bloqueo será equivalente al plazo de prescripción de las acciones derivadas de la relación jurídica que funda el tratamiento en los términos de la Ley aplicable en la materia.</p>
                <p>Una vez cancelado el dato se dará aviso a su titular.</p>
                <p>IV. Oposición.- En todo momento el titular podrá negarse por causa justificada al tratamiento de sus datos personales.</p>
                <p>La solicitud para ejercer los Derechos Arco deberá contener y estar acompañada de lo siguiente: (i) el nombre del titular, su domicilio y/o correo electrónico y cualquier otro medio para comunicarle la respuesta a su solicitud; (ii) los documentos oficiales que acrediten la identidad, o en su caso, la representación legal del titular; (iii) la descripción clara y precisa de los datos respecto de los que se busca ejercer alguno de los derechos antes mencionados; y (iv) cualquier otro elemento o documento que facilite la localización de los datos.</p>
                <p>Recibido el escrito porque se nos indique que hará uso de sus Derecho Arco, tendremos 15 días hábiles para analizar, atender y enviarle la respuesta correspondiente. El medio por el cual le enviaremos nuestra conclusión, será aquel que nos sea indicado por Usted en su solicitud o, en su defecto, por el mismo medio por el cual no hizo llegar su escrito.</p>
                <p>“ARQUIMA” podrá negarle al titular el acceso a sus datos personales, o a realizar la rectificación, cancelación o conceder la oposición al tratamiento de los mismos, en los siguientes casos:</p>
                <p>a) Si es el solicitante, pero no el titular de los datos personales, o su representante legal no esté debidamente acreditado para ello.</p>
                <p>b) Cuando en nuestra base de datos, no se encuentren sus datos personales.</p>
                <p>c) Cuando se lesionen los derechos de un tercero.</p>
                <p>d) Cuando exista un impedimento legal, o la resolución de una autoridad competente, que restrinja el acceso a sus datos personales, o no permita la rectificación, cancelación u oposición de los mismos.</p>
                <p>e) Cuando la rectificación, cancelación u oposición haya sido previamente realizada.</p>
                <p>En todos los casos anteriores, se le informará a usted o en su caso, a su representante legal, el motivo de nuestra decisión y se la comunicaremos, en los plazos establecidos para tal efecto, por el mismo medio por el que se llevó a cabo la solicitud, acompañando, en su caso, las pruebas que resulten pertinentes.</p>
                <p><b>7. Atención al Público</b></p>
                <p>Cualquier cuestión relacionada con la presente Política de Privacidad será atendida en la Oficina de Privacidad de “ARQUIMA”.</p>
                <p><b>8. De los Medios Remotos</b></p>
                <p>Usted entiende y acepta que: (i) nuestro Sitio Web puede incluir enlaces a sitios web de terceros que, en caso de acceder, ocasionará que abandone nuestro sitio web, por lo cual no asumiremos ninguna responsabilidad en relación con los sitios web de terceros; (ii) Nuestro Sitio Web puede incluir enlaces a sitios que administran redes sociales, en cuyo caso Usted acepta que al proporcionar cualquier tipo de información, incluso sus datos en dichos sitios, ocasionará que la misma pueda ser leída, vista, accedida, retrasmitida y tratada por cualquier persona, liberándonos de cualquier responsabilidad; (iii) Es posible que nuestros sistemas recopilen datos adicionales a los que Usted proporcione, como lo son el tipo de navegador, el sistema operativo, las páginas de internet visitadas, la dirección IP, etc., a través de “cookies” o “web beacons”, entre otros. Para poder deshabilitar estos sistemas, deberá acceder a “Opciones de Internet” en la barra de “herramientas” del navegador que utilice.</p>
                <p><b>9. De los Mecanismos de Comunicación</b></p>
                <p>Cualquier comunicación que desee dirigirse con motivo del presente Aviso de Privacidad o para limitar el uso y divulgación de sus Datos, diferentes a los proporcionados para el ejercicio de los Derecho Arco, mencionado de manera clara y precisa: (i) el nombre del titular, su domicilio y/o correo electrónico; (ii) los documentos oficiales que acrediten la identidad, o en su caso, la representación legal del titular; y (iii) el objeto de su comunicación.</p>
                <p><b>10. De las Modificaciones al Aviso de Privacidad </b></p>
                <p>El presente Aviso de Privacidad podrá ser modificado por Nosotros tantas veces como lo consideremos necesario, tanto para guardar congruencia con los ordenamientos legales aplicables, a petición de las autoridades competentes u a nuestra propia conveniencia. En caso de que exista algún cambio a este Aviso de Privacidad, “ARQUIMA” lo comunicará de la siguiente manera: (i) enviándole un correo electrónico a la cuenta que ha registrado en el Sitio Web o proporcionado en otros medios presenciales o electrónicos de recolección de datos y/o (ii) publicando una nota visible en el Sitio Web. “ARQUIMA” no será responsable si usted no recibe la notificación de cambio en el aviso de privacidad si existiere algún problema con su cuenta de correo electrónico o de transmisión de datos por internet. Por su seguridad, revise en todo momento que así lo desee el contenido de este Aviso de Privacidad en nuestro Sitio Web: https://arquima.com.mx</p>
                <p><b>11. Controversias</b></p>
                <p>En caso de que se presente una controversia que se derive del presente Aviso de Privacidad, las partes intentarán primero resolverla a través de negociaciones de buena fe, pudiendo ser asistidos por un mediador profesional. Si después de un máximo de 30 días hábiles de negociación las partes no llegaren a un acuerdo, se estará a lo dispuesto por la Ley Federal de Protección de Datos Personales en Posesión de Particulares, aceptando las partes la intervención que pudiere tener el Instituto Federal de Acceso a la Información y Protección de Datos Personales.</p>
                <p className='mb-3'>Al aceptar este Aviso de Privacidad, usted está de acuerdo en sujetarse a la jurisdicción y competencia de las leyes y tribunales aplicables del Primer Partido Judicial del Estado de Jalisco con sede en la zona metropolitana de la ciudad de Guadalajara, renunciando a partir de este momento a cualquier otra jurisdicción que en razón de su domicilio presente o futuro o por cualquier otra causa les pudiera corresponder.</p>
              </div>
            </Tab>
            <Tab eventKey="terminos" title="Términos y condiciones">
              <div className='text-start'>
                <h6 className='text-center'><b>Términos y condiciones</b></h6>
                <h6 className='text-center mb-3'><b><u>"ARQUIMA"</u></b></h6>
                <p>“SERVICIOS Y ASESORIAS EN ARQUITECTURA ARQUIMA S.A.S. de C.V.”, (en lo sucesivo “ARQUIMA”), le ofrece mediante funciones de sitio web, plataformas de videollamada y plataformas de comunicación (whatsapp), de manera enunciativa pero no limitativa, servicios y asesorias especializadas en promoción, asesoría y trámites en compra-venta de bienes inmuebles; servicios, que serán prestados a su favor de manera presencial y/o mediante móviles o cualquier otro sistema independientemente de los medios de acceso a ellos, tales como computadoras, tablets o similares, lo anterior cuando contrate nuestros servicios, a través del del sitio web: https://www.arquima.com.mx/ o bien, mediante realizando el registro inicial a través de un asesor y contestando la información que se le requiera a través de este medio, misma que usted como usuario podrá revisar en la plataforma mediante un folio o su CURP. Asimismo cuando utilice los servicios de “ARQUIMA” en relación con lo anterior (colectivamente los “Servicios de ARQUIMA”), usted se obliga a cumplir con los siguientes términos y condiciones.</p>
                <p>A todos los “Usuarios” (entendiéndose como cualquier persona que esté registrada y acceda a través de un folio o CURP en la plataforma “ARQUIMA”, mediante equipo de cómputo, celular o cualquier otro medio electrónico), les informamos que los presentes Términos y Condiciones de Uso, les son aplicables por el simple uso o acceso a cualquiera de las Páginas que integran el Portal de “ARQUIMA” y/o a su plataforma de uso respectiva, por lo que entenderemos que los acepta y acuerda en obligarse en su cumplimiento con el simple uso de los servicios de “ARQUIMA”, en el caso de que el usuario no esté de acuerdo con los Términos y Condiciones de Uso y Privacidad deberá abstenerse de acceder, utilizar o consultar el presente Portal.</p>
                <p>El acceso, utilización y/o consulta del Portal y/o a su plataforma de uso respectiva, expresan la adhesión plena y sin reservas del Usuario a los presentes Términos y Condiciones de Uso. A través del Portal y/o a su plataforma de uso respectiva, el Usuario se servirá, contratará y/o utilizará diversos servicios y contenidos puestos a disposición de los Usuarios por los integrantes de “ARQUIMA” y/o por terceros proveedores de Servicios y Contenidos. “ARQUIMA” tendrá el derecho a negar, restringir o condicionar al Usuario el acceso a las Páginas, total o parcialmente, a su entera discreción, así como a modificar los Servicios y Contenidos de las Páginas en cualquier momento y sin necesidad de previo aviso.</p>
                <p className='mb-2'>“ARQUIMA” presta sus servicios mediante la plataforma “http://arquima.com.mx”, que puede ser usada mediante dispositivos móviles y sitios web, la cual facilita el contacto entre personas que requieren los servicios, (Los cuales se describirán más adelante) y las personas que ofrecen dichos servicios, los cuales pueden ser empleados de “ARQUIMA” o terceros contratados a libre discreción de ésta última. </p>
                <p>Los usuarios se sujetan a lo siguiente:</p>
                <p><b>I. Capacidad.</b></p>
                <p>Los Servicios de “ARQUIMA” sólo están disponibles y autorizados para personas que tengan capacidad legal para contratar. No podrán utilizar dichos servicios las personas que no tengan esa capacidad, los menores de edad o Usuarios de “ARQUIMA” que hayan sido suspendidos temporalmente o inhabilitados definitivamente en el uso de dichas facultades, serán dados de baja en cuanto “ARQUIMA” así lo detecte. Si estás registrando un Usuario como Empresa, debes tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos de este Acuerdo.</p>
                <p>Si es usted menor de 18 años de edad, puede usted utilizar los Servicios de “ARQUIMA” únicamente con la participación e involucramiento de uno de sus padres o tutores.</p>
                <p><b>II. Política de privacidad del Sitio Web o Aplicación.</b></p>
                <p>El fundamento de la Política de Privacidad, se sustenta en el cumplimiento que de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares y la Política de Privacidad y Protección de información personal de “ARQUIMA” localizada en este sitio web, debiendo procurar tanto el responsable del presente Sitio, como los usuarios respectivos.</p>
                <p>Toda vez que en el caso de que el Usuario contrate los servicios que ofrece “ARQUIMA” se le requerirá información que pudiera ser considerada de carácter reservado o confidencial, o bien, que pudiera ser catalogada de sensible, por ello, una vez que el Usuario contrate los servicios de mérito y llené los formularios de información respectivos con la citada información, “ARQUIMA” se obliga a tratar confidencialmente y a no divulgarla, siempre y cuando no sea de dominio público y le sea proporcionada por los Usuarios, como consecuencia de las actividades que ésta realizaran en los términos contenidos en los siguientes párrafos.</p>
                <p>Se entenderá por información confidencial, reservada o sensible de los Usuarios, aquella que proporcionen a “ARQUIMA” con motivo de la contratación de los servicios que se llegue a verificar, incluyendo de manera enunciativa pero no limitativa: (i) Los datos, información personal y empresarial, documentos oficiales, fotos, información financiera y de negocios o cualquier otra información de propiedad privada, relacionada con las actividades de los Usuarios; (ii) datos personales, de ocupación laboral y de la empresa en que laboran los Usuarios, o bien, sean Directores o Propietarios, reseña del empresa o grupo en la que laboren, dirijan o sean dueños los Usuarios, nombres y descripciones generales de los negocios diversos de los que formen parte los Usuarios y (iii) cualquier otra que pudiera tener naturaleza de confidencial, reservada o sensible.</p>
                <p>“ARQUIMA” se compromete a resguardar debidamente la información confidencial, reservada o sensible de los Usuarios a la que tenga acceso en virtud de la contratación de servicios que se verifique y no deberá divulgarla a terceros sin el consentimiento previo y por escrito por parte de los Usuarios.</p>
                <p>“ARQUIMA” entiende y reconoce que la información confidencial, reservada o sensible de los Usuarios a la que tenga acceso en virtud de la contratación de servicios que se verifiquen, ha sido desarrollada u obtenida por los Usuarios a través de una considerable inversión de tiempo, esfuerzo, recursos económicos y humanos y que, por tanto, dicha información es para los Usuarios un activo valioso, especial y único y, en consecuencia de ello, requiere estar protegida de cualquier divulgación ilegítima, por lo que “ARQUIMA” se obliga a no revelar, diseminar, compartir, enajenar, transmitir o utilizar dicha información, de cualquier forma o por cualquier motivo, en el presente o futuro, salvo que cuente con el consentimiento previo y por escrito de los Usuarios para tal efecto.  </p>
                <p>Por una parte los usuarios solamente podrán aportar en las diferentes plataformas, aplicaciones y/o páginas insertas en el presente sitio, la información relativa a su persona, sin poder disponer o insertar información de otras personas si no cuentan con la autorización expresa para ello, por lo tanto el usuario se obligará a sacar en paz y a salvo a “ARQUIMA” de cualquier responsabilidad que terceros intenten en contra de este último, por actos u omisiones que el usuario del presente sitio, cometa respecto de los datos personales de terceros que se consideren afectados ya sea porque el uso de sus datos personales se hubiere excedido del uso autorizado al usuario o por que los datos personales hubiesen sido dispuestos sin autorización alguna de su titular.</p>
                <p>“ARQUIMA” realizará el manejo de datos personales e información confidencial de conformidad con el Aviso de Privacidad del presente Sitio.</p>
                <p><b>III. Reglas Generales de Uso.</b></p>
                <p>1. La información, consejos, conceptos y opiniones publicadas en el Sitio Web, no necesariamente reflejan la posición de “ARQUIMA” ni de sus empleados, directores o accionistas. Por lo anterior, “ARQUIMA” no se hace responsable por la información, consejos y opiniones que se emitan en el Sitio Web.</p>
                <p>Aun cuando hacemos esfuerzos importantes para que la información inserta en el Sitio sea completa, veraz y comprobable, es importante señalar que el Sitio permite la inserción de información por parte de los usuarios, por lo tanto, no somos responsables si la información que queda a su disposición en este sitio Web es inexacta o incompleta, razón por la que sugerimos revisarla, cualquier uso de la información del presente Sitio sin verificarla, estará bajo su propio riesgo. Usted manifiesta y está de acuerdo en que es su responsabilidad supervisar cualquier cambio en el material y la información contenida en este sitio Web.</p>
                <p>2. “ARQUIMA” se reserva el derecho de bloquear el acceso o remover en forma parcial o total, toda información, comunicación o material que a su exclusivo juicio pueda resultar: (i) abusivo, difamatorio, obsceno, ofensivo (ii) fraudulento, artificioso o engañoso, (iii) violatorio de derechos de autor, marcas, confidencialidad, secretos industriales o cualquier derecho de propiedad intelectual de un tercero, o (iv) de cualquier forma contravenga lo establecido en los presentes Términos y Condiciones.</p>
                <p><b>IV. Sitio ARQUIMA, Funcionamiento del Servicio y Solicitud del Servicio.</b></p>
                <p>“ARQUIMA” presta sus servicios, el cual consiste, de forma enunciativa mas no limitativa, en servicios de: promoción, asesoría y trámites en compra-venta de bienes inmuebles que serán impartidos por empleados de “ARQUIMA” o terceros contratados a libre discreción de ésta última. </p>
                <p>“ARQUIMA” será responsable por la no prestación de los Servicios pactados reembolsando al Usuario un monto de dinero, pactado previamente, que éste último hubiere hecho por la contratación de los servicios siempre y cuando presente la reclamación a “ARQUIMA” oportunamente, es decir, dentro de las 72 horas siguientes al día en que no se haya verificado la prestación de servicios de mérito mediante notificación por escrito vía whatsapp con el respectivo asesor.</p>
                <p><b>V. Obligaciones de los Usuarios.</b></p>
                <p>Las obligaciones del Usuario, son las que se listan a continuación de manera enunciativa pero no limitativa: (i) cubrir el costo de la contraprestación del servicio, (ii) proveer datos verídicos y ciertos como nombre, datos de contacto y de representación legal en su caso, (iii) sacar en paz y a salvo a “ARQUIMA” en caso de incumplir con los términos de servicio e indemnizar a “ARQUIMA” por cualquier acción legal que resulte en su contra, (iv) contar con la computadora o dispositivo móvil que cumplan con las características y requisitos técnicos para acceder y utilizar los servicios, incluyendo la conexión a internet, (v) no utilizar el Sitio Web para exhibir, transmitir, distribuir o vincular cualquier material que sea falso o engañoso, discriminatorio, difamatorio, ofensivo u obsceno o que pueda incitar a discriminación, odio o violencia contra una persona o grupo de personas a causa de su origen o pertenencia a un grupo étnico, raza o religión, a causa de su género u orientación sexual, (vi) asumir todo el riesgo y responsabilidad por el incumplimiento de estas obligaciones.</p>
                <p><b>VI. Derechos de Autor y Propiedad Industrial.</b></p>
                <p>Todos los derechos de autor y otros derechos de propiedad intelectual en todos los textos, imágenes y otros materiales contenidos en este Sitio Web son propiedad de “ARQUIMA”. Los derechos de autor sobre el contenido, organización, recopilación, información, logotipos, fotografías, imágenes, videos, programas, aplicaciones, o en general cualquier información contenida o publicada en el Sitio Web se encuentra debidamente protegida de conformidad con la legislación aplicable en materia de propiedad intelectual.</p>
                <p>Usted está autorizado a navegar por este Sitio Web, reproducir extractos por medio de impresiones, bajar información al disco duro o con el propósito de distribuir a otros individuos, siempre y cuando, Usted mantenga intacta la información y todos los avisos de Derechos de Autor y de propiedad industrial e intelectual, que aparezcan en las reproducciones. Ninguna reproducción de cualquier parte del Sitio Web puede ser vendida o distribuida con fines de lucro comercial ni debe ser modificada o incorporada en cualquier otro trabajo, publicación o Sitio Web.</p>
                <p>Se prohíbe expresamente al Usuario a modificar, alterar o suprimir, ya sea en forma total o parcial, los avisos, marcas, nombres comerciales, señas, anuncios, logotipos o en general cualquier indicación que se refiere a la propiedad de información contenida en el Sitio Web. El Usuario se obliga a no modificar, reproducir, copiar, rediseñar, descompilar, adaptar, traducir, preparar trabajos derivados de la Aplicación o del Sitio Web o utilizar la Aplicación para desarrollar cualquier software u otros materiales basados en los mismos.</p>
                <p>En caso de que el Usuario diere un uso distinto a la propiedad intelectual de “ARQUIMA”, al conferido por virtud de la contratación de los servicios que se verifique, estará obligado a pagar los daños y perjuicios que se causen a “ARQUIMA”.</p>
                <p><b>VII. Condiciones del Pago</b></p>
                <p>Usted el Usuario, al momento de contratar el servicio de “ARQUIMA”, y liquidar la contraprestación determinada para tales efectos, acepta y reconoce expresamente que no puede cancelarse el servicio de mérito y, por ende, no tendrá derecho alguno de reembolso. Esta Política de no reembolso será aplicable en todo momento, independientemente de su decisión de suspender el uso del Sitio Web o del Servicio. </p>
                <p>“ARQUIMA” podrá, discrecionalmente, hacer ofertas o promocionales con diferentes características y diferentes tasas a cualquiera de los Usuarios. Estas ofertas o promocionales, a menos que se le haga a Usted, no tendrá influencia alguna en su oferta. “ARQUIMA” puede cambiar los precios por el Servicio cuando los considere necesario. Sugerimos revisar periódicamente el Sitio Web con el fin de revisar el precio de los Servicios y cualquier modificación que los mismos pudieren sufrir.</p>
                <p>Usted podrá pagar mediante deposito a la cuenta y transferencia interbancaria mediante los Datos Bancarios que “ARQUIMA” le indique por concepto de contraprestación por los servicios de aseoría y trámites de compra-venta de bienes inmuebles; de igual forma, “ARQUIMA” proporcionará Datos Bancarios en caso de que el Usuario quiera realizar el pago vía SPEI, Tarjeta de Crédito o cualquier otro medio de pago que “ARQUIMA” publique al Usuario, entre sus opciones de pago.</p>
                <p><b>VIII. Deslinde de Responsabilidad</b></p>
                <p>El Usuario está de acuerdo que el uso del Sitio Web obtener y dar segumiento y a sus servicios, se realiza bajo su propio riesgo. “ARQUIMA” no garantiza que (i) el uso del Servicio será seguro, oportuno, ininterrumpido o libre de errores (ii) que el Servicio o el software del Sitio Web cumplirá con sus necesidades o expectativas, (iii) que la calidad de cualquier producto, Servicio, información u otro material obtenido por usted a través del Sitio Web cumplirá al cien por ciento los requerimientos del usuario, sus necesidades o expectativas. </p>
                <p>“ARQUIMA” no asume responsabilidad alguna por los daños y perjuicios de cualquier naturaleza que pudieran derivarse de la utilización de los Servicios y de los contenidos por parte de los Usuarios que puedan derivarse de la falta de veracidad, exhaustividad o autenticidad de la información que los Usuarios proporcionan, incluyendo pero no limitado a los daños y perjuicios que puedan derivarse de la suplantación de la personalidad de un tercero efectuada por un usuario en cualquier clase de comunicación realizada a través del Sitio Web.</p>
                <p><b>IX. Cancelación de Cuenta</b></p>
                <p>Los Usuarios podrán en el momento que así lo deseen, cancelar su cuenta, en cuyo momento “ARQUIMA” garantiza eliminar toda la información de dicho Usuario contenida en su cuenta. El proceso y ejercicio de Derechos ARCO está regulado por el Aviso de Privacidad y la Ley Federal de Protección de Datos Personales. No obstante lo anterior, “ARQUIMA” se reserva el derecho y sin necesidad de aviso previo, de cancelar o suspender el derecho de cualquier Usuario de utilizar los Servicios, y bloquear e impedir su acceso y el uso de los Servicios.</p>
                <p><b>X. Modificaciones a los presentes Términos y Condiciones</b></p>
                <p>“ARQUIMA” se reserva el derecho de modificar en cualquier momento que considere oportuno el contenido de estos Términos y Condiciones pudiendo adicionar provisiones relativas a áreas específicas o nuevos Servicios que en un futuro “ARQUIMA” proporcione a través del Sitio Web, los cuales serán publicadas en el Sitio Web para su lectura y aceptación. Dichas modificaciones formarán parte integrante del presente contrato para todos los efectos legales a que haya lugar. Es responsabilidad de los Usuarios verificar de tiempo en tiempo los presentes Términos y Condiciones para verificar el contenido de los mismos incluyendo cualquier cambio o modificación.</p>
                <p><b>XI. Indemnización</b></p>
                <p>Al hacer uso del Sitio Web y Servicios de “ARQUIMA”, el Usuario consiente en indemnizar a “ARQUIMA”, sus afiliados, accionistas, proveedores, vendedores y asesores de cualquier acción, demanda o reclamación (incluyendo honorarios de abogados y costas judiciales) derivadas de cualquier incumplimiento al presente Contrato por parte del Usuario.</p>
                <p><b>XII. Actividades Prohibidas</b></p>
                <p>Para el uso del presente Sitio, usted tiene prohibido cometer cualquier acto u omisión que a consideración de “ARQUIMA”, pueda contrariar la moral y las buenas costumbres, y/o que pudiera ser considerado como un acto ilegal o que se encuentre prohibido por cualquier ley aplicable a este Sitio Web, incluyendo de manera enunciativa mas no limitativa:</p>
                <p>1. Cualquier acto que pueda constituir una violación en materia de derechos a la privacidad de las personas, confidencialidad y derechos de propiedad intelectual.</p>
                <p>2. Usar este sitio Web para difamar o calumniar a “ARQUIMA”, sus colaboradores o cualquier otro individuo, así como actuar de forma tal que se vea perjudicado el buen nombre de “ARQUIMA”;</p>
                <p>3. Mandar archivos, para cargar en la página, que contengan virus que pueden causar daño a la propiedad de “ARQUIMA” o la propiedad de otros individuos; </p>
                <p>4. Fijar o transmitir a este Sitio Web cualquier material no autorizado, que en nuestra opinión cause molestia, perjuicio o viole sistemas, redes de seguridad resulte difamatorio, racista, obsceno, incluya amenazas, pornografía o cualquier otro elemento ilegal.</p>
                <p>5. Cualquier acto u omisión cuya consecuencia constituya violación a una disposición legal, reglamentaria o normativa, así como aquellos que afecten derechos de terceros o de “ARQUIMA”.</p>
                <p><b>XIII. Legislación Aplicable y Jurisdicción.</b></p>
                Por el simple uso o vista al presente Sitio Web, se desprende una relación e interacción entre el responsable del Sitio y los Usuarios que puede tener diversas consecuencias jurídicas, por ello usted en su carácter de usuario, manifiesta y está de acuerdo en que para la interpretación y cumplimiento de las presentes bases, términos y condiciones, estará de acuerdo en sujetarse a la jurisdicción y competencia de las leyes y tribunales aplicables del Primer Partido Judicial del Estado de Jalisco con sede en la zona metropolitana de la ciudad de Guadalajara, renunciando a partir de este momento a cualquier otra jurisdicción que en razón de su domicilio presente o futuro o por cualquier otra causa les pudiera corresponder.
              </div>
            </Tab>
          </Tabs>
        </Modal.Body>
        <Modal.Footer>
            <Form.Check aria-label="option 1" label="Acepto términos y condiciones" onClick={props.aceptar} />
            { props.terms == true ? (
                <Button variant="primary" onClick={props.onClick} >Aceptar</Button>
                ) : (
                <Button variant="primary" onClick={props.onClick} disabled>Aceptar</Button>
                )
            }
        </Modal.Footer>
      </Modal>
    </>
  );
}

export default ModalTerminos;