export const DB_coto_cielo = [
 {
   "proyecto": "COTO CIELO",
   "folio": 32437,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1288,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "A",
   "lte": 1,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32438,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1280,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "B",
   "lte": 1,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32439,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1013,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "C",
   "lte": 5,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32440,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1281,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "C",
   "lte": 10,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32441,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1000,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 1,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32442,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1002,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 2,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32443,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1004,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 3,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32444,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1006,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 4,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32445,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1008,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 5,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32446,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1010,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 6,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32447,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1012,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 7,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32448,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1014,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 8,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32449,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1016,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 9,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32450,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1030,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 16,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32451,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1032,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 17,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32452,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1042,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "D",
   "lte": 22,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32453,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1011,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 4,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32454,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1013,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 5,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 475300,
   "status": "",
   "nombre": "MAURA BEATRIZ FUENTES ZERMEÑO",
   "esquema": "CONTADO",
   "asesor": "",
   "status_interno": "LIB LIBERADA FIDUCIARIO",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32455,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1039,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 18,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32456,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1041,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 19,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32457,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1043,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 20,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32458,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1045,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 21,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32459,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1038,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 25,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 1078435,
   "status": "",
   "nombre": "MIGUEL FRANCISCO BARAJAS NARES",
   "esquema": "INFONAVIT CONYUGAL",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "22/08/2022",
   "n_escritura": 15609,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32460,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1036,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 26,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 610000,
   "status": "",
   "nombre": "CESAR OSWALDO GONZALEZ TORRES",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "2/6/2022",
   "n_escritura": 15212,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32461,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1034,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 27,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 610000,
   "status": "",
   "nombre": "ALEJANDRA ELIZABETH MARQUEZ VILLARRUEL",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "3/6/2022",
   "n_escritura": 15215,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32462,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1032,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 28,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 650000,
   "status": "",
   "nombre": "LUIS ALBERTO SILVA AMBROSIO",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "18/07/2023",
   "n_escritura": 16566,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32463,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1030,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 29,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 670000,
   "status": "",
   "nombre": "VASQUEZ FUENTES LUIS ENRIQUE",
   "esquema": "INFONAVIT CONYUGAL",
   "asesor": "",
   "status_interno": "LIB LIBERADA FIDUCIARIO",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32464,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1028,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 30,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 650000,
   "status": "",
   "nombre": "MIGUEL ANGEL GARCIA NUÑEZ",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "31/03/2023",
   "n_escritura": 16280,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32465,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1026,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 31,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 650000,
   "status": "",
   "nombre": "LUIS MANUEL AVALOS GUTIERREZ",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "31/03/2023",
   "n_escritura": 16283,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32466,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1024,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 32,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 650000,
   "status": "",
   "nombre": "ARISBETH ESTEFANIA GONZALEZ RAMOS",
   "esquema": "INFONAVIT CONYUGAL",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "13/07/2023",
   "n_escritura": 16543,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32467,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1022,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 33,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 670000,
   "status": "",
   "nombre": "JOSE MIGUEL CABRAL PACHECO",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB LIBERADA FIDUCIARIO",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32468,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1020,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 34,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32469,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1018,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 35,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 650000,
   "status": "",
   "nombre": "MARTIN YONAI ACOSTA VENTUREÑO",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB SOLICITUD DE REEMBOLSO",
   "observaciones": "",
   "fecha_escritura": "15/08/2023",
   "n_escritura": 16644,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32470,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1016,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 36,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 721000,
   "status": "",
   "nombre": "ANDREA DE SAN JUAN ORTIZ PLASCENCIA",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "22/05/2023",
   "n_escritura": 16402,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32471,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1014,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 37,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 638000,
   "status": "",
   "nombre": "YOLANDA REYES PADILLA",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "ANT PRE-VENTA",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32472,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1012,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 38,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 638000,
   "status": "",
   "nombre": "ANA ALEJANDRA GUTIERREZ BAEZA",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "1/3/2023",
   "n_escritura": 16199,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32473,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1010,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 39,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 670000,
   "status": "",
   "nombre": "YULIANA GONZAGA MARTINEZ",
   "esquema": "INFONAVIT CONYUGAL",
   "asesor": "",
   "status_interno": "LIB LIBERADA FIDUCIARIO",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32474,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1008,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 40,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 610000,
   "status": "",
   "nombre": "DANIEL RAVEY CASTILLO",
   "esquema": "CONTADO",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "14/09/2022",
   "n_escritura": 15742,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32475,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1006,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 41,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 638000,
   "status": "",
   "nombre": "ANDRES MARISCAL JIMENEZ",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "15/02/2023",
   "n_escritura": 16157,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32476,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1004,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 42,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32477,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1002,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 43,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32478,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1000,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "E",
   "lte": 44,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32479,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1012,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 7,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32480,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1020,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 11,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32481,
   "direccion": "CALLE DE LA TRANQUILIDAD",
   "numero_ext": 1022,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 12,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32482,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1023,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 13,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 829500,
   "status": "",
   "nombre": "LUIS ANGEL MARTINEZ ALFARO",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "20/04/2023",
   "n_escritura": 16316,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32483,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1021,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 14,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 845000,
   "status": "",
   "nombre": "ALMA LORENA AGUAYO LOPEZ",
   "esquema": "COFINANCIAMIENTO",
   "asesor": "",
   "status_interno": "ANT PRE-VENTA",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32484,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1019,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 15,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 810000,
   "status": "",
   "nombre": "DIANA CITLALI GOMEZ LUGO",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "ANT PRE-VENTA",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32485,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1017,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 16,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32486,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1015,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 17,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 845000,
   "status": "",
   "nombre": "SAMUEL ENRIQUE CRUZ FRANCO",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "ANT PRE-VENTA",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32487,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1013,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 18,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 829500,
   "status": "",
   "nombre": "JOSE CONCEPCION CEDILLO AGUILAR",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "2/5/2023",
   "n_escritura": 16342,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32488,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1011,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 19,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 845000,
   "status": "",
   "nombre": "MORENO AVENDAÑO ANGEL GAMALIEL",
   "esquema": "INFONAVIT CONYUGAL",
   "asesor": "",
   "status_interno": "ANT PRE-VENTA",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32489,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1009,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 20,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 845000,
   "status": "",
   "nombre": "ISIDRO PATIÑO CERVANTES",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "25/07/2023",
   "n_escritura": 16581,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32490,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1007,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 21,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 845000,
   "status": "",
   "nombre": "JORGE MARTINEZ AGUILAR",
   "esquema": "BANCARIO BANREGIO",
   "asesor": "",
   "status_interno": "ANT PRE-VENTA",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32491,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1005,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 22,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 829500,
   "status": "",
   "nombre": "NOE ISRAEL LARES CRUZ",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "27/03/2023",
   "n_escritura": 16261,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32492,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1003,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 23,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 810000,
   "status": "",
   "nombre": "SANDRA MILENA ARIAS GUZMAN",
   "esquema": "CONTADO",
   "asesor": "",
   "status_interno": "LIB LIBERADA FIDUCIARIO",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "GUILLERMO RENTERÍA GIL",
   "n_notaria": 1
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32493,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1001,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "F",
   "lte": 24,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 960250,
   "status": "",
   "nombre": "LUIS ALBERTO TRUJILLO RODRIGUEZ",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB LIBERADA FIDUCIARIO",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32494,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1007,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 1,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 1210850,
   "status": "",
   "nombre": "JOSE SALVADOR MUÑIZ ALCANTAR",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "17/02/2023",
   "n_escritura": 16162,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32495,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1009,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 2,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 755000,
   "status": "",
   "nombre": "PEDRO RICARDO MERCADO MÁRQUEZ",
   "esquema": "INFONAVIT CONYUGAL",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "2/6/2022",
   "n_escritura": 15211,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32496,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1011,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 3,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 829500,
   "status": "",
   "nombre": "EDUARDO ORTIZ PLASCENCIA",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "7/10/2022",
   "n_escritura": 15814,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32497,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1013,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 4,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 755000,
   "status": "",
   "nombre": "LUIS MIGUEL JUAREZ CERVANTES",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "1/7/2022",
   "n_escritura": 15307,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32498,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1015,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 5,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 755000,
   "status": "",
   "nombre": "JOSE BRAULIO NICOLAS CRUZ",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "1/7/2022",
   "n_escritura": 15306,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32499,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1017,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 6,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 790000,
   "status": "",
   "nombre": "JOSE ADRIAN SANDOVAL RAMOS",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "23/09/2022",
   "n_escritura": 15780,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32500,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1019,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 7,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 979000,
   "status": "",
   "nombre": "RIGOBERTO PADILLA LARIOS",
   "esquema": "BANCARIO BBVA",
   "asesor": "",
   "status_interno": "LIB LIBERADA FIDUCIARIO",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "MAYTORENA MARTINEZ NEGRETE JAIME",
   "n_notaria": 86
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32501,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1021,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 8,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 790000,
   "status": "",
   "nombre": "JONATHAN VAZQUEZ ARELLANO",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "8/12/2022",
   "n_escritura": 15983,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32502,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1023,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 9,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 755000,
   "status": "",
   "nombre": "VILLANEY CRUZ SANCHEZ",
   "esquema": "COFINANCIAMIENTO",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "23/09/2022",
   "n_escritura": 31627,
   "nombre_notario": "MAYTORENA MARTINEZ NEGRETE JAIME",
   "n_notaria": 86
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32503,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1025,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 10,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 775000,
   "status": "",
   "nombre": "KEVIN JAIRO PICHARDO GARCIA",
   "esquema": "COFINANCIAMIENTO",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "23/09/2022",
   "n_escritura": 31630,
   "nombre_notario": "MAYTORENA MARTINEZ NEGRETE JAIME",
   "n_notaria": 86
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32504,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1027,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 11,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 875000,
   "status": "",
   "nombre": "MIGUEL ANGEL SERRATOS AGUILAR",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "31/08/2022",
   "n_escritura": 15627,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32505,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1010,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 12,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32506,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1008,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 13,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32507,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1006,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 14,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32508,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1004,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 15,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32509,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1002,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 16,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32510,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1000,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "G",
   "lte": 17,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32511,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1000,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 1,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 945250,
   "status": "",
   "nombre": "IGNACIO REYES CUEVAS",
   "esquema": "INFONAVIT CONYUGAL",
   "asesor": "",
   "status_interno": "LIB DISTRIBUCIÓN CONFIRMADA",
   "observaciones": "",
   "fecha_escritura": "17/03/2023",
   "n_escritura": 16241,
   "nombre_notario": "ESTRADA LOPEZ ELIAS",
   "n_notaria": 5
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32512,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1002,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 2,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 670000,
   "status": "",
   "nombre": "SALAMANCA VELEZ CLARA",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "ANT PRE-VENTA",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32513,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1004,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 3,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 670000,
   "status": "",
   "nombre": "ROJAS MARTINEZ INDRA CITLALLI",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "ANT PRE-VENTA",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32514,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1006,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 4,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32515,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1008,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 5,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32516,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1010,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 6,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32517,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1012,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 7,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32518,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1014,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 8,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32519,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1016,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 9,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 650000,
   "status": "",
   "nombre": "MARIA SOLEDAD RODRIGUEZ MARTINEZ",
   "esquema": "INFONAVIT",
   "asesor": "",
   "status_interno": "ANT PRE-VENTA",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32520,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1018,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 10,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32521,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1020,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 11,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32522,
   "direccion": "CALLE DE LA PAZ",
   "numero_ext": 1022,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 12,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 670000,
   "status": "",
   "nombre": "LILIAN ALEMAN GARCIA",
   "esquema": "INFONAVIT CONYUGAL",
   "asesor": "",
   "status_interno": "ANT PRE-VENTA",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32523,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1023,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 13,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32524,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1021,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 14,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32525,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1019,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 15,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32526,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1017,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 16,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32527,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1015,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 17,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32528,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1013,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 18,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32529,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1011,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 19,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32530,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1009,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 20,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32531,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1007,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 21,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32532,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1005,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 22,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32533,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1003,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 23,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32534,
   "direccion": "CALLE DE LA ESPERANZA",
   "numero_ext": 1001,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "H",
   "lte": 24,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32535,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1000,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 1,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32536,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1004,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 2,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32537,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1008,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 3,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32538,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1012,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 4,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32539,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1016,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 5,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32540,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1020,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 6,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32541,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1024,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 7,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32542,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1028,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 8,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32543,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1032,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 9,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32544,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1036,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 10,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32545,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1040,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 11,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32546,
   "direccion": "CALLE DE LA ARMONIA",
   "numero_ext": 1044,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 12,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32547,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1097,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 13,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32548,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1095,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 14,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32549,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1093,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 15,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32550,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1091,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 16,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32551,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1089,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 17,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32552,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1087,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 18,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32553,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1085,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 19,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32554,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1083,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 20,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32555,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1081,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 21,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32556,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1079,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 22,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32557,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1077,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 23,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32558,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1075,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 24,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32559,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1073,
   "prototipo": "CIMA",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "I",
   "lte": 25,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32560,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1050,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 1,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32561,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1052,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 2,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32562,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1054,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 3,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32563,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1056,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 4,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32564,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1058,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 5,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32565,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1060,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 6,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32566,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1062,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 7,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32567,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1064,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 8,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32568,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1066,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 9,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32569,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1068,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 10,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32570,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1070,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 11,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32571,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1072,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 12,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32572,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1074,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 13,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32573,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1076,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 14,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32574,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1078,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 15,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32575,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1080,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 16,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32576,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1082,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 17,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32577,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1084,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 18,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32578,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1086,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 19,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32579,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1088,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 20,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32580,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1090,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 21,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32581,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1092,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 22,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32582,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1094,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 23,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32583,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1096,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 24,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 },
 {
   "proyecto": "COTO CIELO",
   "folio": 32584,
   "direccion": "CIRCUITO DEL CIELO",
   "numero_ext": 1098,
   "prototipo": "ALTUS",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": "J",
   "lte": 25,
   "m2_terreno": "",
   "m2_const": "",
   "precio": 0,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": null,
   "nombre_notario": "",
   "n_notaria": null
 }
]