export const DB_rosario = [
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1301",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 1,
   "m2_terreno": 101.6,
   "m2_const": "",
   "precio": 558800,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1302",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 2,
   "m2_terreno": 100.12,
   "m2_const": "",
   "precio": 550660,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1303",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 3,
   "m2_terreno": 112.49,
   "m2_const": "",
   "precio": 618695,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1304",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 4,
   "m2_terreno": 96.55,
   "m2_const": "",
   "precio": 579300,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1305",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 5,
   "m2_terreno": 97.63,
   "m2_const": "",
   "precio": 566254,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1306",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 6,
   "m2_terreno": 98.32,
   "m2_const": "",
   "precio": 570256,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1307",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 7,
   "m2_terreno": 98.92,
   "m2_const": "",
   "precio": 573736,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1308",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 8,
   "m2_terreno": 105.85,
   "m2_const": "",
   "precio": 582175,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1309",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 9,
   "m2_terreno": 106.12,
   "m2_const": "",
   "precio": 583660,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1310",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 10,
   "m2_terreno": 106.72,
   "m2_const": "",
   "precio": 586960,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1311",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 11,
   "m2_terreno": 107.32,
   "m2_const": "",
   "precio": 590260,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1312",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 12,
   "m2_terreno": 107.69,
   "m2_const": "",
   "precio": 592295,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1313",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 13,
   "m2_terreno": 106.37,
   "m2_const": "",
   "precio": 585035,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1314",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 14,
   "m2_terreno": 104.72,
   "m2_const": "",
   "precio": 607376,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1315",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 15,
   "m2_terreno": 118,
   "m2_const": "",
   "precio": 684400,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1316",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 16,
   "m2_terreno": 166.5,
   "m2_const": "",
   "precio": 999000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1317",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 17,
   "m2_terreno": 114.22,
   "m2_const": "",
   "precio": 628210,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1318",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 18,
   "m2_terreno": 115.3,
   "m2_const": "",
   "precio": 634150,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "ROSARIO",
   "folio": "ROS1319",
   "direccion": "JUAN GIL PRECIADO",
   "numero_ext": "SN",
   "prototipo": "CREDITERRENO",
   "inmueble": "TERRENO",
   "nivel": "",
   "mz": 1,
   "lte": 19,
   "m2_terreno": 160.85,
   "m2_const": "",
   "precio": 820335,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 }
]