export const DB_san_antonio = [
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1001",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 1,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 1,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1002",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 3,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 2,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1003",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 5,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 3,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1004",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 7,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 4,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1005",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 9,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 5,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1006",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 11,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 6,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1007",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 13,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 7,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1008",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 15,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 8,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1009",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 17,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 9,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1010",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 19,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 10,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1011",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 21,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 11,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1012",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 23,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 12,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1013",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 25,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 13,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1014",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 27,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 14,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1015",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 29,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 15,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1016",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 31,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 16,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1017",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 33,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 17,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1018",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 35,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 18,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1019",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 37,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 19,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1020",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 39,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 20,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1021",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 41,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 21,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1022",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 43,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 22,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1023",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 45,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 23,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1024",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 47,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 24,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1025",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 49,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 25,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1026",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 51,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 26,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1027",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 53,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 27,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1028",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 55,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 28,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1029",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 57,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 29,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1030",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 59,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 30,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1031",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 61,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 31,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1032",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 63,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 32,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1033",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 65,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 33,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1034",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 67,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 34,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1035",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 69,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 35,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1036",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 71,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 36,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1037",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 73,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 37,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1038",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 75,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 38,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1039",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 77,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 39,
   "m2_terreno": 90,
   "m2_const": "",
   "precio": 635000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 },
 {
   "proyecto": "SAN ANTONIO",
   "folio": "SA1040",
   "direccion": "SAN IDELFONSO",
   "numero_ext": 79,
   "prototipo": "SAN ANTONIO",
   "inmueble": "HABITACIONAL UNIFAMILIAR",
   "nivel": "",
   "mz": 22,
   "lte": 40,
   "m2_terreno": 151.35,
   "m2_const": "",
   "precio": 895000,
   "status": "LIBRE",
   "nombre": "",
   "esquema": "",
   "asesor": "",
   "status_interno": "",
   "observaciones": "",
   "fecha_escritura": "",
   "n_escritura": "",
   "nombre_notario": "",
   "n_notaria": ""
 }
]