export const statusOpciones = [
    "LIBRE",
    "ARMADO DE EXPEDIENTE",
    "EN PROCESO AVALUO",
    "EN PROCESO AUTORIZACION",
    "AUTORIZACION",
    "DICTAMINACION",
    "EN PROGRAMACION DE FIRMA",
    "FIRMADO",
    "EN PROCESO DE PAGO INSTITUCION BANCARIA",
    "PAGADO, PROGRAMACION DE ENTREGA",
    "FECHA DE ENTREGA"
]

