export const compras = [
    "contado",
    "FOVISSSTE-infonavit-fovissste",
    "FOVISSSTE-tradicional",
    "FOVISSSTE-conyugal",
    "FOVISSSTE-para-todos",
    "INFOVANIT-tradicional",
    "INFOVANIT-unamos-creditos",
    "INFOVANIT-conyugal",
    "INFOVANIT-infonavit-fovissste",
    "INFOVANIT-crediterreno",
    "INFOVANIT-segundo-credito",
    "INFOVANIT-cofinativ",
    "IPEJAL-tradicional",
    "IPEJAL-terreno",
    "IPEJAL-conyugal",
    "BANCARIO-terreno",
    "BANCARIO-casa"
]